sudo: required

language: node_js
node_js:
    - "10"
services:
    - docker

script:
    - docker run --rm -v "$(pwd)" node:10 bash -c "npm install -g vuepress@next && npm build"
cache:
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: .vuepress/dist
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: jamcha-aa/Requiem-novel
    keep-history: true
    target-branch: gh-pages
    on:
        branch: master
